name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export PATH="$PATH:/root/.nvm/versions/node/v22.2.0/bin/"
            cd /var/apps/camcaroni-attendance
            git restore pnpm-lock.yaml
            git pull
            pnpm install
            pnpm build
            rm -rf /var/apps/camcaroni-attendance/dist/views
            cp -r /var/apps/camcaroni-attendance/src/views /var/apps/camcaroni-attendance/dist/views
            pm2 restart asistencia-camcaroni
            pm2 save